[package]
name = "neovm-core"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Core runtime structures for NeoVM"

[dependencies]
neovm-host-abi = { path = "../neovm-host-abi" }
regex = "1"
